[nxp]
name = "NXP Semiconductors"
desc = "Next Experience"
more = "A Dutch semiconductor designer and manufacturer with headquarters in Eindhoven, Netherlands. The company employs approximately 31,000 people in more than 30 countries."
