[smt.PCB]
name = "SMT"
desc = "Surface-Mount Technology"
see = 'THT'

[st]
name = "ST"
desc = "SGS Microelettronica and Thomson Semiconducteurs"
more = "The company resulted from the merger of two government-owned semiconductor companies in 1987: Thomson Semiconducteurs of France and SGS Microelettronica of Italy. It is commonly called ST, and it is Europe's largest semiconductor chip maker based on revenue"
